module.exports = {
  firstSidebar: {
    "Crab Network": [
      'crab-home', 
      'crab-tools', 
      'crab-parameters'
    ],

    'Tutorials': [
      'crab-tut-create-account',
      'crab-tut-claim-cring',
      'crab-tut-node',
      {
        'Staking': [
          'crab-tut-validator',
          'crab-tut-nominator'
        ]
      },
      'crab-tut-exchange'
    ],

    "Kusama Auction": [
      'crab-crowdloan',
      'crab-crowdloan-howto-unstaking',
      'crab-crowdloan-howto-polkadotjs',
      'crab-crowdloan-howto-okex',
      'crab-crowdloan-howto-math',
      'crab-crowdloan-howto-gateio',
      'crab-crowdloan-howto-hotbit'
    ],

    "DVM": [
      'dvm-intro',
      {
        'Overview': [
          'dvm-address',
          'dvm-system-contract'
        ]
      },
      {
        'Wallets': [
          'dvm-apps',
          'dvm-metamask', 
          {
            'Smart App':[
              'dvm-smart-app',
              'dvm-deposit',
              'dvm-withdraw'
            ]
          }
        ]
      },
      'dvm-explorer',
      {
        'Interaction': [
          'dvm-rpc',
          {
            'Contract': [
              'dvm-remix',
              'dvm-web3-contract',
              'dvm-web3-transfer'
            ]
          },
          {
              'Indexers': [
                  'dvm-thegraph'
              ]
          }
        ]
      },
      'dvm-eco',
      {
        'Builders':[
          {
            type: 'autogenerated',
            dirName: 'builders', // Generate sidebar slice from docs/guides
          },
        ]
      }
    ],                  

    'Pangolin Testnet': [
      'pangolin-home',
      {
        'Bridges': [
          'pangolin-bridge-ropsten'
        ]
      }
    ]
  },
  'Builders': [
  ]

};
